language: erlang
notifications:
  recipients:
    - josh.rubyist@gmail.com
otp_release:
  - R16B
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test --no-start
env:
  - MIX_ENV=test
